AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for Black Arrow VPC.'

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::ID>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
Resources:
# Company VPC Footprint
  BlackArrowVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '172.16.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: 'blackarrow-vpc'
        - Key: Text
          Value: 'Created via Custom CloudFormation Template'
        - Key: Owner
          Value: Eric Francis-Chief Architect/Lead DevOps Engineer

  PublicSubnet1A:
  #Company Public Subnet in AZ1
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref BlackArrowVPC
      CidrBlock: '172.16.1.0/24'
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet1A
        - Key: Text
          Value: 'Created via Custom CloudFormation Template'
        - Key: Owner
          Value: Eric Francis-Chief Architect/Lead DevOps Engineer

  AppPrivateSubnet1A:
  #Company App Private Subnet in AZ1
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref BlackArrowVPC
      CidrBlock: '172.16.2.0/24'
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: AppPrivateSubnet1A
        - Key: Text
          Value: 'Created via Custom CloudFormation Template'
        - Key: Owner
          Value: Eric Francis-Chief Architect/Lead DevOps Engineer

  DataPrivateSubnet1A:
  #Company Data Private Subnet in AZ1
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref BlackArrowVPC
      CidrBlock: '172.16.3.0/24'
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: DataPrivateSubnet1A
        - Key: Text
          Value: 'Created via Custom CloudFormation Template'
        - Key: Owner
          Value: Eric Francis-Chief Architect/Lead DevOps Engineer

  PublicSubnet2A:
  #Company Public Subnet in AZ2
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref BlackArrowVPC
      CidrBlock: '172.16.4.0/24'
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet2A
        - Key: Text
          Value: 'Created via Custom CloudFormation Template'
        - Key: Owner
          Value: Eric Francis-Chief Architect/Lead DevOps Engineer

  AppPrivateSubnet2A:
  #Company App Private Subnet in AZ2
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref BlackArrowVPC
      CidrBlock: '172.16.5.0/24'
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: AppPrivateSubnet2A
        - Key: Text
          Value: 'Created via Custom CloudFormation Template'
        - Key: Owner
          Value: Eric Francis-Chief Architect/Lead DevOps Engineer

  DataPrivateSubnet2A:
  #Company Data Private Subnet in AZ2
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref BlackArrowVPC
      CidrBlock: '172.16.6.0/24'
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: DataPrivateSubnet2A
        - Key: Text
          Value: 'Created via Custom CloudFormation Template'
        - Key: Owner
          Value: Eric Francis-Chief Architect/Lead DevOps Engineer

  #Internet Gateway
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: blackarrow-igw
        - Key: Text
          Value: 'Created via Custom CloudFormation Template'
        - Key: Owner
          Value: Eric Francis-Chief Architect/Lead DevOps Engineer

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref BlackArrowVPC
      InternetGatewayId: !Ref InternetGateway

  #Route Tables
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref BlackArrowVPC
      Tags:
        - Key: Name
          Value: PublicRouteTable
        - Key: Text
          Value: 'Created via Custom CloudFormation Template'
        - Key: Owner
          Value: Eric Francis-Chief Architect/Lead DevOps Engineer

  #Public Routes
  PublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref InternetGateway

  #Subnet Associations
  PublicSubnet1AAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet1A
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2AAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet2A
      RouteTableId: !Ref PublicRouteTable

  # BlackArrow Web Server / Application Load Balancer Security Group
  BlackArrowWebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for BlackArrow Web Server and ALB
      VpcId: !Ref BlackArrowVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: BlackArrowWebServerSecurityGroup
        - Key: Text
          Value: 'Created via Custom CloudFormation Template'
        - Key: Owner
          Value: Eric Francis-Chief Architect/Lead DevOps Engineer

  # BlackArrow Launch Template  
  BlackArrowLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: 't3.micro'
        MetadataOptions:
          HttpTokens: required
          HttpEndpoint: enabled
        SecurityGroupIds:
          - !Ref BlackArrowWebServerSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Greetings from BlackArrow Web Server ASG </h1>" > /var/www/html/index.html

  # BlackArrow Auto Scaling Group
  BlackArrowAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    DependsOn:
      - PublicRoute
      - PublicSubnet1AAssociation
      - PublicSubnet2AAssociation
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref BlackArrowLaunchTemplate
        Version: !GetAtt BlackArrowLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '5'
      DesiredCapacity: '2'
      VPCZoneIdentifier:
        - !Ref PublicSubnet1A
        - !Ref PublicSubnet2A
      Tags:
        - Key: Name
          Value: BlackArrowAutoScalingGroup
          PropagateAtLaunch: true
        - Key: Text
          Value: 'Created via Custom CloudFormation Template'
          PropagateAtLaunch: true
        - Key: Owner
          Value: Eric Francis-Chief Architect/Lead DevOps Engineer
          PropagateAtLaunch: true
# Alarm
  BlackArrowCPUAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Alarm if CPU exceeds 70%'
      MetricName: 'CPUUtilization'
      Namespace: 'AWS/EC2'
      Statistic: 'Average'
      Period: '300'
      EvaluationPeriods: '1'
      Threshold: '70'
      ComparisonOperator: 'GreaterThanThreshold'
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref BlackArrowAutoScalingGroup
      AlarmActions:
        - !Ref BlackArrowScaleOutPolicy

# BlackArrow Scale Out Policy
  BlackArrowScaleOutPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AutoScalingGroupName: !Ref BlackArrowAutoScalingGroup
      PolicyType: SimpleScaling
      AdjustmentType: ChangeInCapacity
      Cooldown: 300
      ScalingAdjustment: 1

      
