AWSTemplateFormatVersion: "2010-09-09"
Description: 'IAM Cloudformation Template for BlackArrow'

Resources:
  BlackArrowIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'SoleymanCFN'
      ManagedPolicyArns:
       - 'arn:aws:iam::aws:policy/AdministratorAccess'

  # BlackArrowIAMGroup
  BlackArrowIAMGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: 'BlackArrowAdmins'
  
  # Attach User To Group
  BlackArrowIAMUserToGroupAttachment:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref BlackArrowIAMGroup
      Users:
        - !Ref BlackArrowIAMUser
  # IAM Role For EC2
  BlackArrowRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
       - 'arn:aws:iam::aws:policy/PowerUserAccess'

  #S3 Custom Policy

  BlackArrowS3Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'CustomPolicy'
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 's3:GetObject'
            Resource: '*'
      Roles:
        - !Ref BlackArrowRole

        
